name: convay_hls_player_example
description: Example app for ConvayHlsPlayer.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  convay_hls_player:
    path: ../
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
