name: convay_hls_player
description: ConvayHlsPlayer widget for seamless HLS playback with token refresh.
version: 1.0.2
homepage: https://github.com/Synesis-IT-PLC/convay-hls-player-flutter-sdk
repository: https://github.com/Synesis-IT-PLC/convay-hls-player-flutter-sdk

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  # better_player:
  #   path: ./better_player-0.0.84
  http: ^1.2.2
  collection: ^1.19.1
  wakelock_plus: ^1.4.0
  path_provider: ^2.1.5
  visibility_detector: ^0.4.0+2
  flutter_widget_from_html_core: ^0.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.5

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: uz.shs.better_player_plus
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: SwiftBetterPlayerPlugin