name: convay_hls_player
description: Simple HLS player using better_player.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # better_player:
  #   path: ./better_player-0.0.84
  http: ^1.2.2
  collection: ^1.19.1
  wakelock_plus: ^1.4.0
  path_provider: ^2.1.5
  visibility_detector: ^0.4.0+2
  flutter_widget_from_html_core: ^0.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.5

flutter:
  uses-material-design: true
